-- TO CREATE A DATABASE 
CREATE DATABASE EDUCATION_LOAN 
CREATE DATABASE SHAVERSHOP_SALES

--TO CHANGE THE NAME OF DATABASE
ALTER DATABASE EDUCATION_LOAN
MODIFY NAME = STUDENT_LOAN 

--HOW TO USE A PARTICULAR DATABASE OUT OF ALL DATABASES 
--NOTE: WE CANNOT DELETE ANY DATABASE PERMENANTLY WHEN IT IS IN USE 
USE STUDENT_LOAN 

--TO DELETE THE DATABASE PERMENANTLY 
DROP DATABASE SHAVERSHOP_SALES


/*
--HOW TO CREATE A TABLE 

TO CREATE A TABLE INSIDE ANY PARTICULAR DATABASE WE NEED TO USE THAT DATABASE AND
USE CREATE FUNCTION 
WRITE THE NAMES OF THE COLUMN AND THEIR DATATYPES 

*/
CREATE TABLE STUDENT_INFO
(
NAME VARCHAR(25),
STUDENT_ID INT, 
COURSE_NAME VARCHAR(30),
SECTION VARCHAR(3),
MOBILE_NUMBER BIGINT
)

SELECT * FROM STUDENT_INFO -- HERE WE USING * TO TELL WE WANTED TO SEE ALL THE COLUMNS INSIDE THE TABLE 

-- ADDING DATA INTO THE TABLE USING INSERT COMMAND 

INSERT INTO STUDENT_INFO VALUES ('Harika', 23186016, 'Computer Science', 'A', 0223892440), ('Nikitha', 23186023, 'Health Science', 'B', 0224897525)

-- HOW TO RENAME A TABLE 
EXEC SP_RENAME STUDENT_INFO, STUDENT_INFORMATION 

-- NOW THAT WE CHANGED THE TABLE NAME WE SHOULD AGAIN USE SELECT COMMANDS TO SEE THE VALUES IN THE TABLE 
SELECT * FROM STUDENT_INFORMATION

-- HOW TO RENAME A COLUMN INSIDE THE TABLE 
-- WE USED:
-- EXEC SP_RENAME 'TABLE NAME.COLUMN NAME', 'NEW COLUMN NAME', 'COLUMN'
-- WE CAN SEE AT THE END WE USE COLUMN WORD IT DOESN'T REFLECT WITHOUT USING COLUMN 


EXEC SP_RENAME 'STUDENT_INFORMATION.NAME', 'STUDENT_NAME', 'COLUMN'

-- TO CHANGE THE DATATYPE OF A COLUMN INSIDE A TABLE 
ALTER TABLE STUDENT_INFORMATION
ALTER COLUMN MOBILE_NUMBER BIGINT 

-- TO ADD A COLUMN TO THE TABLE WE DON'T NEED TO SAY THE COLUMN COMMAND TO ADD A COLUMN

ALTER TABLE STUDENT_INFORMATION
ADD LOCATION VARCHAR(50)

-- TO DROP A COLUMN INSIDE THE TABLE 
ALTER TABLE STUDENT_INFORMATION
DROP COLUMN LOCATION

INSERT INTO STUDENT_INFORMATION (EMPLOYEE_NAME) VALUES ('PRASHU') -- IS USED TO ADD A NEW ROW 

-- IF WE WANTED TO UPDATE EXISTING VALUES
-- WE USE UPDATE COMMAND 
/*
FOR THIS WE NEED TO USE
UPDATE TABLE NAME
SET COLUMN NAME - 'WHICHEVER VALUE WE WANTED'
*/

UPDATE STUDENT_INFORMATION 
SET EMPLOYEE_NAME = 'Prashu'
WHERE ROLL_NO = NULL


SELECT * FROM STUDENT_INFORMATION 

-- HOW TO IMPORT DATA FROM CSV FILE
-- IMPORTING DATA INTO EXISTING TABLE - BULK INSERT IS USED

CREATE TABLE EDUCATION_LOAN 
(
APPLICANT_NAME VARCHAR(35),
AGE INT,
PHONE_NUMBER BIGINT, 
EMAIL VARCHAR(50)
)

SELECT * FROM EDUCATION_LOAN 

BULK INSERT 
FROM "https://d.docs.live.net/8D5449EAB93C53D2/Documents/Harik_informaTION.csv.xlsx"
WITH (FORMAT = 'CSV', FIRST_ROW = 2)



-- PRACTICE TEST 01 

/*
Create a new database called
SCHOOL_DB and use it

Create a table called STUDENTS with these columns:

STUDENT_ID - whole number
STUDENT_NAME - text up to 50 chars
AGE - whole number
SECTION - single character
MARKS - whole number
CITY - text up to 50 chars
EMAIL - text up to 100 chars
DOB - date

Insert 10 students with 
these details:

1, Priya, 17, B, 72, Delhi
2, Amit, 16, A, 95, Mumbai
3, Sneha, 17, C, 65, Chennai
4, Vikram, 16, B, 80, Delhi
5, Pooja, 17, A, 91, Mumbai
6, Kiran, 16, C, 55, Chennai
7, Arjun, 17, B, 78, Delhi
8, Deepa, 16, A, 84, Mumbai
9,Rohan, 17, 'C', 60, Chennai
You decide the emails and DOB!

Once the table is created solve these questions
   
Q1. View all students

Q2. View only STUDENT_NAME and MARKS

Q3. Get all students from Mumbai

Q4. Get students with marks greater than 80

Q5. Get students in Section A

Q6. Sort students by marks lowest to highest

Q7. Get the highest marks

Q8. Get the lowest marks

Q9. Get the average marks

Q10. Count total students

Q11. Get students with marks between 70 and 90

Q12. Get students from Delhi and Chennai using IN

Q13. Get students NOT from Mumbai

Q14. Sort by CITY ascending and MARKS descending

Q15. Get students in Section A with marks above 85

Q16. Get total marks of all Mumbai students

Q17. Get count of students in each SECTION

Q18. Get average marks per city

Q19. Add a new column called GRADE VARCHAR(5)

Q20. Update GRADE to A where marks >= 80

Q21. Update GRADE to B where marks between 70 and 79

Q22. Update GRADE to C where marks below 70

Q23. Write CASE statement showing PASS if marks >= 70 and FAIL if below 70

Q24. Get all students where GRADE is NULL

Q25. Drop the EMAIL column
*/

CREATE DATABASE SCHOOL_DB
USE SCHOOL_DB

CREATE TABLE STUDENTS_DETAILS
(
STUDENT_ID INT,
STUDENT_NAME VARCHAR(50),
AGE INT,
SECTION VARCHAR,
MARKS INT,
CITY VARCHAR(500), 
EMAIL VARCHAR(100),
DOB DATE
)

-- TO INSERT VALUES INSIDE THE TABLE CREATED 
INSERT INTO STUDENTS_DETAILS VALUES (1,'Rahul', 16, 'A', 88, 'Mumbai', 'brgr@gmail.com', '2004-04-27'),
(2,'Priya', 17, 'B', 72, 'Delhi', 'ergrgr@gmail.com', '2001-05-24'),
(3,'Amit', 16, 'A', 95, 'Mumbai', 'ergr@gmail.com', '2006-02-01'),
(4,'Sneha', 17, 'C', 65, 'Chennai', 'ergbgr@gmail.com', '2002-07-28'),
(5,'Vikram', 16, 'B', 80, 'Delhi', 'rgr@gmail.com', '2012-03-17'),
(6,'Pooja', 17, 'A', 91, 'Mumbai', 'frr@gmail.com', '2005-09-04'),
(7,'Arjun', 17, 'B', 78, 'Delhi', 'emgr@gmail.com', '2003-06-26'),
(8,'Deepa', 16, 'A', 84, 'Mumbai', 'erfsfgr@gmail.com', '2008-07-22'),
(9,'Rohan', 17, 'C', 60, 'Chennai', 'ervsrr@gmail.com', '2011-07-09')

SELECT * FROM STUDENTS_DETAILS

SELECT STUDENT_NAME, MARKS FROM STUDENTS_DETAILS 

SELECT STUDENT_NAME, CITY FROM STUDENTS_DETAILS WHERE CITY = 'MUMBAI'

SELECT STUDENT_NAME, MARKS FROM STUDENTS_DETAILS WHERE MARKS > 80 

SELECT STUDENT_NAME, SECTION FROM STUDENTS_DETAILS WHERE SECTION = 'A'

SELECT STUDENT_NAME, MARKS FROM STUDENTS_DETAILS ORDER BY MARKS ASC 

SELECT MAX(Marks) FROM STUDENTS_DETAILS 

SELECT MIN(Marks) FROM STUDENTS_DETAILS 

SELECT AVG(Marks) FROM STUDENTS_DETAILS 

SELECT COUNT(STUDENT_NAME) FROM STUDENTS_DETAILS 


SELECT STUDENT_NAME, MARKS FROM STUDENTS_DETAILS WHERE MARKS > 70 AND MARKS < 90

SELECT STUDENT_NAME, CITY FROM STUDENTS_DETAILS WHERE CITY IN ('Delhi', 'Mumbai')

SELECT STUDENT_NAME, CITY FROM STUDENTS_DETAILS WHERE CITY != 'Mumbai'

SELECT CITY, MARKS FROM STUDENTS_DETAILS ORDER BY CITY ASC, MARKS DESC 

SELECT SUM(MARKS) FROM STUDENTS_DETAILS WHERE CITY = 'Mumbai'

SELECT SECTION ,COUNT(STUDENT_NAME) FROM STUDENTS_DETAILS GROUP BY SECTION 

SELECT CITY, AVG(MARKS) FROM STUDENTS_DETAILS GROUP BY CITY 

ALTER TABLE STUDENTS_DETAILS 
ADD GRADE VARCHAR(5)

UPDATE STUDENTS_DETAILS 
SET GRADE = 'A'
WHERE MARKS >= 80 



UPDATE STUDENTS_DETAILS 
SET GRADE = 'B' 
WHERE MARKS >= 70 AND MARKS <= 79

UPDATE STUDENTS_DETAILS 
SET GRADE = 'B'
WHERE MARKS < 70 

SELECT *,
CASE 
WHEN MARKS >= 70 THEN 'PASS'
ELSE 'FAIL'
END AS CHECK_STATUS
FROM STUDENTS_DETAILS 

SELECT STUDENT_NAME 
FROM STUDENTS_DETAILS 
WHERE GRADE IS NULL 

ALTER TABLE STUDENTS_DETAILS
DROP COLUMN EMAIL

